### PR TITLE
Fix latest monorepo issue

### LINKED ISSUE #76: Failed step "analyzeCommits" of plugin "[Function: ]"
When trying to run `semantic-release -e semantic-release-monorepo --dry-run`

With no release config in `package.json`...

I run into the following error:

```
[23:25:21] [semantic-release] › ✖  Failed step "analyzeCommits" of plugin "[Function: ]"
[23:25:21] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Expected `moduleId` to be of type `string`, got `object`
```

Here's the full output:

```
[23:25:14] [semantic-release] › ℹ  Running semantic-release version 15.13.30
[23:25:15] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[23:25:15] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[23:25:15] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[23:25:15] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[23:25:15] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[23:25:15] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[23:25:15] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[23:25:15] [semantic-release] › ⚠  Run automated release from branch master in dry-run mode
[23:25:19] [semantic-release] › ✔  Allowed to push to the Git repository
[23:25:19] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[23:25:19] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[23:25:19] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[23:25:19] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[23:25:19] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[23:25:21] [semantic-release] › ℹ  No git tag version found
[23:25:21] [semantic-release] › ℹ  No previous release found, retrieving all commits
[23:25:21] [semantic-release] › ℹ  Found 9 commits since last release
[23:25:21] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: ]"
[23:25:21] [semantic-release] › ✖  Failed step "analyzeCommits" of plugin "[Function: ]"
[23:25:21] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/<path-to-project>/node_modules/resolve-from/index.js:11:9)
    at module.exports (/<path-to-project>/node_modules/resolve-from/index.js:34:41)
    at module.exports (/<path-to-project>/node_modules/semantic-release-plugin-decorators/node_modules/import-from/index.js:4:49)
    at requirePlugin (/<path-to-project>/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/<path-to-project>/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /<path-to-project>/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/<path-to-project>/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at /<path-to-project>/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (/<path-to-project>/node_modules/p-reduce/index.js:17:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  pluginName: '[Function: ]'
}
TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/<path-to-project>/node_modules/resolve-from/index.js:11:9)
    at module.exports (/<path-to-project>/node_modules/resolve-from/index.js:34:41)
    at module.exports (/<path-to-project>/node_modules/semantic-release-plugin-decorators/node_modules/import-from/index.js:4:49)
    at requirePlugin (/<path-to-project>/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/<path-to-project>/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /<path-to-project>/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/<path-to-project>/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at /<path-to-project>/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (/<path-to-project>/node_modules/p-reduce/index.js:17:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  pluginName: '[Function: ]'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```

### PR DESCRIPTION
**Pull request by hweeks**
This fixes the latest issue from semantic-release 15.13.31 at least

[Fixes #76]

### CODE REVIEW

**Comment by hweeks** [comment]
@pmowrer Is there something I'd need to do to get this reviewed and merged? This is a blocker for latest `semantic-release`. I've got some ideas on how to go about determining which wrapper function to use, but I wanted to land a fix ASAP.

**Comment by pmowrer** [comment]
@hweeks Thanks for the PR! I can merge but still waiting to have the npm package rights transferred to me. Hoping this will happen in the next week or two

**Comment by brettdorrans** [comment]
@pmowrer Any luck on this yet?

Even a merge would be useful to unblock me, so I could point to the repo.

**Comment by hweeks** [comment]
@brettdorrans you can fork this and release under `@brettdorrans/semantic-release-monorepo

**Comment by brettdorrans** [comment]
@hweeks Yeah, I've done so under a fork, cheers. @pmowrer this package is very useful but a bit flaky sometimes - are you looking for maintainers?

**Comment by pmowrer** [comment]
@brettdorrans I haven't been able to make any updates in over a year because the repo belonged to my former employer. It was recently transferred over to me but I'm still waiting on the npm package to transfer.

**Comment by hweeks** [comment]
Once this is done up, I'd love to take a stab at supporting v16 among other things.

**Comment by mc0** [comment]
@pmowrer is this still blocked? Should you just make a fork (and rename the package) if you can't get the npm package?

**Comment by pmowrer** [comment]
@mc0 @hweeks Thanks for your patience! I've now got all the access I need and will start digging into this... I'll probably look at https://github.com/pmowrer/semantic-release-plugin-decorators/pull/9 first though.

**Comment by folke** [comment]
FYI: I made a very small package that pretty much does everything that **semantic-release-monorepo** does and it's compatible with the latest semantic-release version.

It might be a good idea to look at the code and see if you could use it here. See https://github.com/folke/semantic-release-commit-filter/blob/master/src/index.ts

> Since I couldn't get this package to work properly, I've created a small package :package: [semantic-release-commit-filter](https://www.npmjs.com/package/semantic-release-commit-filter) that adds commit filtering for the current working directory to `semantic-release`.
> The implementation is only about **20 lines** of code. It works by hijacking calls to the `git-log-parser` `parse` method.
> What does it do?
> * filters commits for the current working directory
> * configures a default `tagFormat` including the package name.
> 
> As far as I understand, this provides pretty much the same functionality as `semantic-release-monorepo`
> Just add `"semantic-release-commit-filter"` to your `extends` configuration, or run `semantic-release` with `-e  semantic-release-commit-filter`. No special or additional config changes are required.

**Comment by pmowrer** [comment]
@folke At first glance, your solution (while still a hack 😉) is better - way less brittle (and frustrating) than monkey-patching the ever changing plugin API. I'd be happy to use it in this repo, either directly or use the plugin itself in the configuration that this repo exports. 

That said, beyond commit filtering, there isn't much else done by `semantic-release-monorepo`... I think it's just [the release notes version header](https://github.com/pmowrer/semantic-release-monorepo#generatenotes). Maybe there's more stuff needed with `semantic-release` v16... I'm a bit out of the loop with all of this.

**Comment by hweeks** [comment]
I had an idea that might fix some of these issues automatically that’s not as brittle as injecting changes to posix, though it’s a cool solution. Any desire to convert to typescript?

**Comment by pmowrer** [comment]
@hweeks @mc0 @brettdorrans I've pushed up a branch that I believe will fix the problem. Would any of you be able to test it out? https://github.com/pmowrer/semantic-release-monorepo/pull/80

**Comment by pmowrer** [comment]
This problem should be resolved as of [v7.0.0](https://github.com/pmowrer/semantic-release-monorepo/releases/tag/v7.0.0).

**Pull request closed without merging**
